###############################################################################
# IAM identity providers (federation primitives)
#
# This composite co-owns the account-level OIDC and SAML identity providers.
# Each is independently optional via its own configuration object, but AT LEAST
# ONE must be supplied — a provider with neither configured manages nothing.
#
# OIDC is the recommended path: CI/CD pipelines (GitHub Actions / Azure DevOps)
# assume IAM roles via short-lived web-identity tokens, so no static AWS keys are
# stored anywhere. SAML is co-managed when enterprise SSO into IAM is needed.
###############################################################################

variable "oidc" {
 description = <<EOT
OpenID Connect (OIDC) identity provider configuration, rendered as one
aws_iam_openid_connect_provider. Leave null to manage no OIDC provider (then a
saml object is required). One provider per unique issuer URL per account.

 - url: HTTPS issuer URL of the IdP, corresponding to the iss
 claim (e.g. "https://token.actions.githubusercontent.com").
 REQUIRED. FORCE-NEW — changing it replaces the provider.
 - client_id_list: Audiences (aud) that identify the apps registered with the
 IdP (e.g. ["sts.amazonaws.com"]). REQUIRED, non-empty — no
 wildcard audience is baked in; the caller owns the boundary.
 - thumbprint_list: Optional server-certificate CA thumbprints (40-char hex) to
 pin. For major IdPs (GitHub, GitLab, Google, Auth0, or an
 S3-hosted JWKS) AWS validates against its own trusted CA
 library and any value here is retained but unused. Omit to
 let IAM auto-retrieve the thumbprint for other IdPs.
 - tags: Extra tags merged over module tags for this provider.

 oidc = {
 url = "https://token.actions.githubusercontent.com"
 client_id_list = ["sts.amazonaws.com"]
 }
EOT
 type = object({
 url = string
 client_id_list = list(string)
 thumbprint_list = optional(list(string))
 tags = optional(map(string), {})
 })
 default = null

 validation {
 condition = var.oidc != null || var.saml != null
 error_message = "At least one identity provider must be configured: supply an oidc object, a saml object, or both."
 }

 validation {
 condition = var.oidc == null || can(regex("^https://", coalesce(try(var.oidc.url, null), "x")))
 error_message = "oidc.url must be an HTTPS issuer URL (begins with 'https://')."
 }

 validation {
 condition = var.oidc == null || length(try(var.oidc.client_id_list, [])) > 0
 error_message = "oidc.client_id_list must contain at least one audience (no wildcard audience is allowed)."
 }

 validation {
 condition = try(var.oidc.thumbprint_list, null) == null || alltrue([for t in coalesce(try(var.oidc.thumbprint_list, null), []): can(regex("^[0-9a-fA-F]{40}$", t))])
 error_message = "Each oidc.thumbprint_list entry must be a 40-character hexadecimal SHA-1 certificate thumbprint."
 }
}

variable "saml" {
 description = <<EOT
SAML 2.0 identity provider configuration, rendered as one aws_iam_saml_provider.
Leave null to manage no SAML provider (then an oidc object is required). One
provider per unique metadata document per account.

 - name: Name of the SAML provider. REQUIRED. FORCE-NEW —
 changing it replaces the provider. Account-unique.
 - saml_metadata_document: The federation metadata XML document generated by
 the IdP that supports SAML 2.0. REQUIRED. Load with
 file("metadata.xml") or pass the XML string.
 - tags: Extra tags merged over module tags for this provider.

 saml = {
 name = "corp-okta"
 saml_metadata_document = file("$${path.module}/okta-metadata.xml")
 }
EOT
 type = object({
 name = string
 saml_metadata_document = string
 tags = optional(map(string), {})
 })
 default = null

 validation {
 condition = var.saml == null || can(regex("^[a-zA-Z0-9._-]{1,128}$", coalesce(try(var.saml.name, null), "x")))
 error_message = "saml.name must be 1-128 characters of letters, digits, and the characters _. -"
 }
}

###############################################################################
# Universal tail
###############################################################################

variable "tags" {
 description = <<EOT
A map of tags to assign to every taggable resource created by this module (the
OIDC provider and, when created, the SAML provider). These merge with
provider-level default_tags; resource tags win on key conflict, and per-provider
tags (oidc.tags / saml.tags) win over these module-level tags. The computed
tags_all output reflects the fully merged set.
EOT
 type = map(string)
 default = {}
}
